export const adminConsoleNavGroups = [
  {
    key: 'operations-home',
    label: '运营首页',
    icon: 'home',
    items: [
      {
        key: 'business-overview',
        label: '经营总览',
        icon: 'dashboard',
        path: '/admin/overview',
        sidebarSection: 'admin',
        sidebarModule: 'overview',
      },
      {
        key: 'realtime-monitor',
        label: '实时监控',
        icon: 'activity',
        path: '/admin/realtime-monitor',
        sidebarSection: 'admin',
        sidebarModule: 'realtime_monitor',
      },
      {
        key: 'channel-alerts',
        label: '渠道预警',
        icon: 'health',
        path: '/admin/channel-alerts',
        sidebarSection: 'admin',
        sidebarModule: 'channel_alerts',
      },
    ],
  },
  {
    key: 'channel-operations',
    label: '渠道运营',
    icon: 'channel',
    items: [
      {
        key: 'channels',
        label: '渠道管理',
        icon: 'channel',
        path: '/admin/channels',
        aliases: ['/console/channel'],
        sidebarSection: 'admin',
        sidebarModule: 'channel',
      },
      {
        key: 'channel-accounts',
        label: '账号池管理',
        icon: 'database',
        path: '/admin/channel-accounts',
        aliases: ['/console/channel/accounts'],
        sidebarSection: 'admin',
        sidebarModule: 'channel_account',
      },
      {
        key: 'channel-balance-monitor',
        label: '渠道余额监控',
        icon: 'wallet',
        path: '/admin/channel-balance-monitor',
        aliases: ['/console/channel-balance-monitor'],
        sidebarSection: 'admin',
        sidebarModule: 'channel_balance_monitor',
      },
      {
        key: 'channel-health-check',
        label: '渠道健康检测',
        icon: 'health',
        path: '/admin/channel-health-check',
        aliases: ['/console/channel-health-check'],
        sidebarSection: 'admin',
        sidebarModule: 'channel_health_check',
      },
      {
        key: 'channel-proxies',
        label: '代理管理',
        icon: 'network',
        path: '/admin/channel-proxies',
        aliases: ['/console/channel-proxies'],
        sidebarSection: 'admin',
        sidebarModule: 'channel_proxy',
      },
    ],
  },
  {
    key: 'models-routing',
    label: '模型与路由',
    icon: 'model',
    items: [
      {
        key: 'model-gateway',
        label: '智能模型网关',
        icon: 'bot',
        path: '/admin/model-gateway',
        aliases: ['/console/model-gateway'],
        sidebarSection: 'console',
        sidebarModule: 'model_gateway',
      },
      {
        key: 'models',
        label: '模型管理',
        icon: 'model',
        path: '/admin/models',
        aliases: ['/console/models'],
        sidebarSection: 'admin',
        sidebarModule: 'models',
      },
      {
        key: 'deployment',
        label: '模型部署',
        icon: 'package',
        path: '/admin/deployment',
        aliases: ['/console/deployment'],
        sidebarSection: 'admin',
        sidebarModule: 'deployment',
      },
      {
        key: 'route-policy',
        label: '路由策略',
        icon: 'sliders',
        path: '/admin/route-policy',
        sidebarSection: 'admin',
        sidebarModule: 'route_policy',
      },
      {
        key: 'ratio-config',
        label: '倍率配置',
        icon: 'settings',
        path: '/admin/ratio-config',
        sidebarSection: 'admin',
        sidebarModule: 'ratio_config',
      },
    ],
  },
  {
    key: 'commercial-operations',
    label: '商业运营',
    icon: 'dollar',
    items: [
      {
        key: 'profit-monitor',
        label: '盈利监控台',
        icon: 'dollar',
        path: '/admin/profit-monitor',
        aliases: ['/console/profit-monitor'],
        sidebarSection: 'admin',
        sidebarModule: 'profit_monitor',
      },
      {
        key: 'subscription',
        label: '订阅管理',
        icon: 'package',
        path: '/admin/subscription',
        aliases: ['/console/subscription'],
        sidebarSection: 'admin',
        sidebarModule: 'subscription',
      },
      {
        key: 'redemption',
        label: '兑换码管理',
        icon: 'gift',
        path: '/admin/redemption',
        aliases: ['/console/redemption'],
        sidebarSection: 'admin',
        sidebarModule: 'redemption',
      },
      {
        key: 'settlements',
        label: '结算记录',
        icon: 'receipt',
        path: '/admin/settlements',
        sidebarSection: 'admin',
        sidebarModule: 'settlements',
      },
      {
        key: 'consumption',
        label: '消费明细',
        icon: 'logs',
        path: '/admin/consumption',
        sidebarSection: 'admin',
        sidebarModule: 'consumption',
      },
    ],
  },
  {
    key: 'user-operations',
    label: '用户运营',
    icon: 'users',
    items: [
      {
        key: 'users',
        label: '用户管理',
        icon: 'users',
        path: '/admin/users',
        aliases: ['/console/user'],
        sidebarSection: 'admin',
        sidebarModule: 'user',
      },
      {
        key: 'user-segments',
        label: '用户分层',
        icon: 'shield',
        path: '/admin/user-segments',
        sidebarSection: 'admin',
        sidebarModule: 'user_segments',
      },
      {
        key: 'risk-records',
        label: '风控记录',
        icon: 'shield',
        path: '/admin/risk-records',
        sidebarSection: 'admin',
        sidebarModule: 'risk_records',
      },
      {
        key: 'invite-rebates',
        label: '邀请返佣',
        icon: 'gift',
        path: '/admin/invite-rebates',
        sidebarSection: 'admin',
        sidebarModule: 'invite_rebates',
      },
    ],
  },
  {
    key: 'system-governance',
    label: '系统治理',
    icon: 'settings',
    items: [
      {
        key: 'settings',
        label: '系统设置',
        icon: 'settings',
        path: '/admin/settings',
        aliases: ['/console/setting'],
        sidebarSection: 'admin',
        sidebarModule: 'setting',
      },
      {
        key: 'roles',
        label: '权限角色',
        icon: 'shield',
        path: '/admin/roles',
        sidebarSection: 'admin',
        sidebarModule: 'roles',
      },
      {
        key: 'audit-logs',
        label: '审计日志',
        icon: 'logs',
        path: '/admin/audit-logs',
        sidebarSection: 'admin',
        sidebarModule: 'audit_logs',
      },
      {
        key: 'background-tasks',
        label: '后台任务',
        icon: 'receipt',
        path: '/admin/background-tasks',
        sidebarSection: 'admin',
        sidebarModule: 'background_tasks',
      },
    ],
  },
];
