export const userConsoleNavGroups = [
  {
    key: 'overview',
    label: '概览',
    icon: 'dashboard',
    items: [
      {
        key: 'dashboard',
        label: '数据看板',
        icon: 'dashboard',
        path: '/console',
        sidebarSection: 'console',
        sidebarModule: 'detail',
      },
      {
        key: 'service-status',
        label: '服务状态',
        icon: 'activity',
        path: '/console/channel-status',
        sidebarSection: 'console',
        sidebarModule: 'channel_status',
      },
    ],
  },
  {
    key: 'developer',
    label: '开发接入',
    icon: 'code',
    items: [
      {
        key: 'playground',
        label: '操练场',
        icon: 'code',
        path: '/console/playground',
        sidebarSection: 'chat',
        sidebarModule: 'playground',
      },
      {
        key: 'tokens',
        label: '令牌管理',
        icon: 'key',
        path: '/console/token',
        sidebarSection: 'console',
        sidebarModule: 'token',
      },
      {
        key: 'usage-logs',
        label: '使用日志',
        icon: 'logs',
        path: '/console/log',
        sidebarSection: 'console',
        sidebarModule: 'log',
      },
      {
        key: 'drawing-logs',
        label: '绘图日志',
        icon: 'sparkles',
        path: '/console/midjourney',
        sidebarSection: 'console',
        sidebarModule: 'midjourney',
      },
      {
        key: 'task-logs',
        label: '任务日志',
        icon: 'receipt',
        path: '/console/task',
        sidebarSection: 'console',
        sidebarModule: 'task',
      },
    ],
  },
  {
    key: 'billing',
    label: '费用中心',
    icon: 'wallet',
    items: [
      {
        key: 'recharge',
        label: '账户充值',
        icon: 'creditCard',
        path: '/console/recharge',
        sidebarSection: 'personal',
        sidebarModule: 'recharge',
      },
      {
        key: 'subscription-plans',
        label: '套餐订阅',
        icon: 'package',
        path: '/console/subscription-plans',
        sidebarSection: 'personal',
        sidebarModule: 'subscription_plans',
      },
      {
        key: 'affiliate',
        label: '邀请有奖',
        icon: 'gift',
        path: '/console/affiliate',
        sidebarSection: 'personal',
        sidebarModule: 'affiliate',
      },
    ],
  },
];
